# Generated by Django 4.2 on 2023-04-22 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="hashtag",
            new_name="hashtags",
        ),
    ]
