# Generated by Django 4.2 on 2023-04-23 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_post_liked_by_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
    ]
