# Generated by Django 4.2 on 2023-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_comment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="schedule",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
