# Generated by Django 4.2 on 2023-04-22 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_followed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followed_by",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
